application: donordb
version: 1
runtime: python
api_version: 1


builtins:
- datastore_admin: on

handlers:
- url: /stylesheets
  static_dir: stylesheets
  login: admin

- url: /.*
  script: donor.py
  login: required
